frame1:
  ylabel:
    text: '$\Delta\sigma_{\mathrm{fid}}\,/\,\Delta m_{jj}\ \mathrm{(fb/GeV)}$'
    fontsize: 18
  ylim:
    bottom: 0
    top: 0.06
  fontsize: 13
  title_fontsize: 13

frame2:
  fontsize: 13
  title_fontsize: 13
  ytick_labels:
    is_data:
      - "0.0"
      - "0.5"
      - "1.0"
      - "1.5"
      - "2.0"
      - "2.5"
    not_data:
      - "0.0"
      - "0.5"
      - "1.0"
      - "1.5"
      - "2.0"
      - "2.5"
  yticks:
    is_data:
      - 0.0
      - 0.5
      - 1.0
      - 1.5
      - 2.0
      - 2.5
    not_data:
      - 0.0
      - 0.5
      - 1.0
      - 1.5
      - 2.0
      - 2.5
