frame1:
  custom_xtick_labels:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4+"
  custom_xticks:
    - 0.5
    - 1.5
    - 2.5
    - 3.5
    - 4.5
  ylabel:
    text: '$\sigma_{\text{fid}}$ (fb)'
    fontsize: 20
  ylim:
    bottom: 0
  fontsize: 14
  title_fontsize: 14

frame2:
  xtick_labels:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4+"
  xticks:
    - 0.5
    - 1.5
    - 2.5
    - 3.5
    - 4.5
  ytick_labels:
    is_data:
      - "0.0"
      - "1.0"
      - "2.0"
      - "3.0"
      - "4.0"
    not_data:
      - "0.0"
      - "0.5"
      - "1.0"
      - "1.5"
      - "2.0"
      - "2.5"
  yticks:
    is_data:
      - 0
      - 1
      - 2
      - 3
      - 4
    not_data:
      - 0
      - 0.5
      - 1
      - 1.5
      - 2
      - 3
