lumi: 172
cms_rlabel: "172 $\\mathrm{fb^{-1}}$ (13.6 TeV)"
cms_label_fontsize: 22

frame1:
  axvline:
    - x: 100
      color: "black"
      ls: "-"
      lw: 1
      alpha: 1
    - x: 200
      color: "black"
      ls: "-"
      lw: 1
      alpha: 1
  ylabel:
    text: '$\Delta\sigma_{\mathrm{fid}} / \Delta p_{t}$ (fb/GeV)'
    fontsize: 20
  ylim:
    bottom: 0.0002
    top: 16000
  additional_labels:
    - text: '$n_{\mathrm{jets}}=0$'
      position: [5, 3]
      rotation: 0
      fontsize: 18
    - text: '$n_{\mathrm{jets}}=1$'
      position: [103, 3]
      rotation: 0
      fontsize: 18
    - text: '$n_{\mathrm{jets}}\geq2$'
      position: [205, 3]
      rotation: 0
      fontsize: 18
    - text: '$\frac{\sigma_{fid}(p_{T}^{H} > 60\ \mathrm{GeV})}{20\ \mathrm{GeV}}$'
      position: [80, 0.6]
      rotation: 90
      fontsize: 16
    - text: '$\frac{\sigma_{fid}(p_{T}^{H} > 170\ \mathrm{GeV})}{80\ \mathrm{GeV}}$'
      position: [180, 0.04]
      rotation: 90
      fontsize: 16
    - text: '$\frac{\sigma_{fid}(p_{T}^{H} > 350\ \mathrm{GeV})}{100\ \mathrm{GeV}}$'
      position: [281, 0.01]
      rotation: 90
      fontsize: 16
  fontsize: 13
  title_fontsize: 13

frame2:
  xtick_fontsize: 16
  ytick_fontsize: 18
  xlabel_fontsize: 20
  ylabel_fontsize: 18
  xtick_rotation: 0
  xtick_labels:
    - "0"
    - "20"
    - "40"
    - "60"
    - "0"
    - "50"
    - "100"
    - "150"
    - "200"
    - "0"
    - "100"
    - "200"
    - "300"
    - "400"
  xticks:
    - 0
    - 25
    - 50
    - 75
    - 100
    - 120
    - 140
    - 160
    - 180
    - 200
    - 222.222
    - 244.444
    - 266.667
    - 288.889
  ytick_labels:
    is_data:
      - "0.0"
      - "1.0"
      - "2.0"
    not_data:
      - "0.0"
      - "1.0"
      - "2.0"
  yticks:
    is_data:
      - 0
      - 1.0
      - 2.0
    not_data:
      - 0
      - 1.0
      - 2.0
  axvline:
    - x: 100
      color: "black"
      ls: "-"
      lw: 1
      alpha: 1
    - x: 200
      color: "black"
      ls: "-"
      lw: 1
      alpha: 1
