# Config file: options for signal fitting

backgroundScriptCfg:
  # Setup
  inputWS: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/CMSSW_14_1_0_pre4/src/flashggFinalFit/law/output/input_output_data_PTH_2022/ws/allData.root' # location of 'allData.root' file
  cats: 'auto' # auto: automatically inferred from input ws
  catOffset: 0 # add offset to category numbers (useful for categories from different allData.root files)
  # ext: 'earlyAnalysis_PTH' # extension to add to output directory
  # year: '2022' # Use combined when merging all years in category (for plots)

trees2wsCfg:
  # Name of RooDirectory storing input tree
  inputTreeDir: 'DiphotonTree'

  # Variables to be added to dataframe: use wildcard * for common strings
  mainVars:
    - "CMS_hgg_mass"
    - "weight"
    - "weight_central"
    - "dZ"
    - "*Up"
    - "*Down"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH"
  
  dataVars:
    - "CMS_hgg_mass"
    - "weight" # Vars to be added for data
    
  stxsVar: ''
  diffVar: 'diffVariable_GenPTH'
  notagVars: [] # Vars to add to NOTAG RooDataset
  
  systematicsVars:
    - "CMS_hgg_mass"
    - "weight"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH" # Variables to add to systematic RooDataHists
  
  theoryWeightContainers:
    weight_LHEPdf: 101
    weight_LHEScale: 9

  # List of systematics: use string YEAR for year-dependent systematics
  systematics:
    - "ScaleEB"
    - "ScaleEE"
    - "Smearing"
    - "Material"
    - "FNUF"
    - "energyErrShift"
    - "JerSyst"
    - "JecSy"

  cats: 'auto'