# Config file: options for signal fitting

outputFolder: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/CMSSW_14_1_0_pre4/src/flashggFinalFit/law/output/forPaper_24_09_06/'

inputFiles:
  # Trees2WS
  Trees2WSData: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/devel/Run3HggNtuples/analysis_Ntuples/forPaper_24_09_06/data/root/Data/allData_2022.root'
  Trees2WS: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/devel/Run3HggNtuples/analysis_Ntuples/forPaper_24_09_06/with_categorization/signal/signal_postprocessing/root'

backgroundScriptCfg:
  # Setup
  cats: 'auto' # auto: automatically inferred from input ws
  catOffset: 0 # add offset to category numbers (useful for categories from different allData.root files)
  ext: 'earlyAnalysis' # extension to add to output directory
  # year: '2022' # Use combined when merging all years in category (for plots)

trees2wsCfg:
  # Name of RooDirectory storing input tree
  inputTreeDir: 'DiphotonTree'

  # Variables to be added to dataframe: use wildcard * for common strings
  mainVars:
    - "CMS_hgg_mass"
    - "weight"
    - "weight_central"
    - "dZ"
    - "*Up"
    - "*Down"
    - "fiducialGeometricFlag"
  
  dataVars:
    - "CMS_hgg_mass"
    - "weight" # Vars to be added for data
    
  stxsVar: ''
  diffVar: ''
  notagVars: [] # Vars to add to NOTAG RooDataset
  
  systematicsVars:
    - "CMS_hgg_mass"
    - "weight"
    - "fiducialGeometricFlag"
  
  theoryWeightContainers:
    weight_LHEPdf: 101
    weight_LHEScale: 9

  # List of systematics: use string YEAR for year-dependent systematics
  systematics:
    - "ScaleEB"
    - "ScaleEE"
    - "Smearing"
    - "Material"
    - "FNUF"
    - "energyErrShift"

  cats: 'auto'

signalScriptCfg_2022_preEE:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_2022preEE' # output directory extension
  analysis: 'earlyAnalysisInOut' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2022preEE' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary

  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  beamspotWidthData: '3.2'
  beamspotWidthMC: '3.732'


  # Job submission options
  batch: 'local' # ['condor_lxplus','condor','SGE','IC','local']
  queue: 'microcentury' # use hep.q for IC

signalScriptCfg_2022_postEE:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_2022postEE' # output directory extension
  analysis: 'earlyAnalysisInOut' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2022postEE' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary

  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  
  beamspotWidthData: '3.5'
  beamspotWidthMC: '3.732'

  # Job submission options
  batch: 'local' # ['condor_lxplus','condor','SGE','IC','local']
  queue: 'microcentury' # use hep.q for IC
