# Config file: options for signal fitting

outputFolder: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/CMSSW_14_1_0_pre4/src/flashggFinalFit/law/output/forPaper_24_10_07_PTH/'

inputFiles:
  # Trees2WS
  Trees2WSData: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/devel/EOSCMS/2024/ntuples/forPaper_24_10_07/variables/PTH/data_postprocessing/root/Data/allData_2022.root'
  Trees2WS: '/afs/cern.ch/user/n/niharrin/cernbox/PhD/Higgs/devel/EOSCMS/2024/ntuples/forPaper_24_10_07/variables/PTH/signal_postprocessing/root'

backgroundScriptCfg:
  # Setup
  cats: 'auto' # auto: automatically inferred from input ws
  catOffset: 0 # add offset to category numbers (useful for categories from different allData.root files)
  ext: 'earlyAnalysis_PTH' # extension to add to output directory
  # year: '2022' # Use combined when merging all years in category (for plots)

trees2wsCfg:
  inputTreeDir: 'DiphotonTree' # Name of RooDirectory storing input tree

  apply_mass_cut: False # Apply cut on CMS_hgg_mass
  mass_cut_range: '100,180' # CMS_hgg_mass cut range
  doSTXSSplitting: False # Split output WS per STXS bin
  doDiffSplitting: True # Split output WS per differential bin
  doInOutSplitting: False # Split output WS into in/out fiducial based on some variable in the input trees (to be improved).
  doSystematics: True # Add systematics datasets to output WS

  # Variables to be added to dataframe: use wildcard * for common strings
  mainVars:
    - "CMS_hgg_mass"
    - "weight"
    - "weight_central"
    - "dZ"
    - "*Up"
    - "*Down"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH"
  
  dataVars:
    - "CMS_hgg_mass"
    - "weight" # Vars to be added for data
    
  stxsVar: ''
  diffVar: 'diffVariable_GenPTH'
  notagVars: [] # Vars to add to NOTAG RooDataset
  
  systematicsVars:
    - "CMS_hgg_mass"
    - "weight"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH"
  
  theoryWeightContainers:
    weight_LHEPdf: 101
    weight_LHEScale: 9

  # List of systematics: use string YEAR for year-dependent systematics
  systematics:
    - "ScaleEB"
    - "ScaleEE"
    - "Smearing"
    - "Material"
    - "FNUF"
    - "energyErrShift"
    - "JerSyst"
    - "JecSystTotal"

  cats: 'auto'

signalScriptCfg_2022_preEE:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_PTH_2022preEE' # output directory extension
  analysis: 'earlyAnalysisDiffPt' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2022preEE' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary

  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  doPlots: True

  beamspotWidthData: '3.2'
  beamspotWidthMC: '3.732'


  # Job submission options
  batch: 'local' # ['condor_lxplus','condor','SGE','IC','local']
  queue: 'microcentury' # use hep.q for IC

signalScriptCfg_2022_postEE:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_PTH_2022postEE' # output directory extension
  analysis: 'earlyAnalysisDiffPt' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2022postEE' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary

  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  doPlots: True

  beamspotWidthData: '3.5'
  beamspotWidthMC: '3.732'

  # Job submission options
  batch: 'local' # ['condor_lxplus','condor','SGE','IC','local']
  queue: 'microcentury' # use hep.q for IC

packaged_2022:
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  massPoints: '120,125,130' # You can now run with a single mass point if necessary
  mergeYears: True # Merges the eras
  ext: ''

datacard_yields:
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  procs: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis' # Extension for saving
  # inputWSDirMap: '2022preEE,2022postEE'
  sigModelWSDir: './Models_PTH/signal' # Input signal model WS directory
  bkgModelWSDir: './Models_PTH/background' # Input background model WS directory
  bkgModelExt: 'multipdf' # Extension used when saving background model
  doSystematics: True # Include systematics calculations and add to datacard
  mergeYears: True # Merge category across years
  skipZeroes: True # Skip signal processes with 0 sum of weights
  ignore_warnings: True # Skip errors for missing systematics. Instead output warning message
  mass: '125' # Input workspace mass
  skipBkg: False # Only add signal processes to datacard
  bkgScaler: 1. # Add overall scale factor for background
  skipCOWCorr: False # Skip centralObjectWeight correction for events in acceptance. Use if no centralObjectWeight in workspace

datacard:
  # For pruning processes
  prune: True # Prune proc x cat which make up less than pruneThreshold (default 0.1%) of given total category
  pruneThreshold: 0.001 # Threshold with which to prune proc x cat as fraction of total category yield (default=0.1%)
  doTrueYield: False # For pruning: use true number of expected events for proc x cat i.e. Product(XS,BR,eff*acc,lumi). Use only if NOTAG dataset has been included. If false then will use nominal_yield (i.e. sumEntries)
  analysis: 'earlyAnalysis' # Analysis extension: required for doTrueYield (see ./tools/XSBR.py for example)

  # For yield/systematics:
  skipCOWCorr: False # Skip centralObjectWeight correction for events in acceptance
  doSystematics: True # Include systematics calculations and add to datacard
  doMCStatUncertainty: True # Add uncertainty for MC stats
  doSTXSMerging: False # Calculate additional migrations uncertainties for merged STXS bins (for 'mnorm' tier in systematics)
  doSTXSScaleCorrelationScheme: False # Partially de-correlate scale uncertainties for different phase space regions

  # For output:
  saveDataFrame: False # Save final dataframe as pkl file
  output: 'Datacard_PTH_2022' # Datacard name

datacard_clean:
  factor: 10000 # Factor beyond which uncertainty is considered incorrect and is removed
  removeDoubleSided: False # Remove any nuisances which are listed as antisymmetric but both values point the same way
  removeNonDiagonal: False # Remove any nuisances which are affect processes unimportant in that category
  symmetrizeNuisance: 'CMS_hgg_SigmaEOverEShift,CMS_hgg_scale_0_shape,CMS_hgg_scale_1_shape,CMS_hgg_scale_3_shape' # Symmetrizes asymmetric nuisance. Enter in the format nuisance1,nuisance2,nuisance3,etc.
  verbose: False # Spit out all the cleaning being done
